# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='タイトル')),
                ('timestamp', models.CharField(max_length=255, verbose_name='最終更新日')),
            ],
        ),
    ]
