# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20151224_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url_list',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='url_list',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='url_list',
            name='url',
            field=models.URLField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
