# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_crawled_url_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='JVN_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, unique=True, verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('date', models.DateTimeField(verbose_name='YearDateTime')),
            ],
        ),
        migrations.AddField(
            model_name='crawled_url_list',
            name='html_digest',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hash'),
        ),
    ]
