# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_dictionary_about_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary_about_security',
            name='word',
            field=models.CharField(max_length=63, unique=True, verbose_name='word'),
        ),
    ]
