# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_auto_20160108_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JVN_list',
        ),
    ]
